language: csharp
os: 
  - linux

dist: xenial 
sudo: required
mono: none
dotnet: 2.2.203
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
     - libunwind8

  
git:
  depth: false

script:
- dotnet restore Build.csproj
- dotnet flubu rebuild.linux -s=BuildScript/BuildScript.cs
