version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    dotnet restore FlubuCore

    dotnet restore dotnet-flubu

    dotnet restore Flubu.Tests

    dotnet pack FlubuCore -c Release --version-suffix %APPVEYOR_BUILD_NUMBER%

    dotnet pack dotnet-flubu -c Release --version-suffix %APPVEYOR_BUILD_NUMBER%

    appveyor PushArtifact dotnet-flubu\bin\Release\dotnet-flubu.1.0.0-%APPVEYOR_BUILD_NUMBER%.nupkg

    appveyor PushArtifact FlubuCore\bin\Release\FlubuCore.1.0.0-%APPVEYOR_BUILD_NUMBER%.nupkg
test_script:
- cmd: dotnet test Flubu.Tests -xml results.xml
notifications:
- provider: Email
  to:
  - zoro.zorec@gmail.com
  - mzorec@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true