version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    dotnet restore project.json --no-cache

    dotnet flubu compile

    appveyor PushArtifact dotnet-flubu\bin\Release\dotnet-flubu.1.0.%APPVEYOR_BUILD_NUMBER%.nupkg

    appveyor PushArtifact FlubuCore\bin\Release\FlubuCore.1.0.%APPVEYOR_BUILD_NUMBER%.nupkg
test_script:
- cmd: dotnet test Flubu.Tests -xml results.xml
notifications:
- provider: Slack
  auth_token:
    secure: 7XqzccV11cUEmlu5fVc5Hh8NB3FFauquscxGGbryn03f3fRzSOFsoMwcbVPiYnnS
  channel: #appveyor
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true